"""Initial migration

Revision ID: 6b675e6e872d
Revises: 
Create Date: 2025-08-21 06:37:38.532211

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b675e6e872d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_tickets')
    with op.batch_alter_table('mechanics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('mechanic_email'))

    op.drop_table('mechanics')
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('vin'))

    op.drop_table('tickets')
    with op.batch_alter_table('customer_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('customer_email'))

    op.drop_table('customer_accounts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_accounts',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_name', mysql.VARCHAR(length=75), nullable=False),
    sa.Column('customer_phone', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('customer_email', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('customer_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('customer_email'), ['customer_email'], unique=True)

    op.create_table('tickets',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticket_date', mysql.DATETIME(), nullable=False),
    sa.Column('vin', mysql.VARCHAR(length=17), nullable=False),
    sa.Column('service_desc', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('customer_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_accounts.id'], name='tickets_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('vin'), ['vin'], unique=True)

    op.create_table('mechanics',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mechanic_name', mysql.VARCHAR(length=75), nullable=False),
    sa.Column('mechanic_phone', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('mechanic_salary', mysql.FLOAT(), nullable=False),
    sa.Column('mechanic_email', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('mechanics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('mechanic_email'), ['mechanic_email'], unique=True)

    op.create_table('service_tickets',
    sa.Column('ticket_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mechanic_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['mechanic_id'], ['mechanics.id'], name=op.f('service_tickets_ibfk_2')),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('service_tickets_ibfk_1')),
    sa.PrimaryKeyConstraint('ticket_id', 'mechanic_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
